apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-cluster-sentinel-d1
spec:
  replicas: 4
  selector:
    matchLabels:
      app: redis-cluster-sentinel-lbl
  template:
    metadata:
      name: redis-cluster-sentinel-p1
      labels:
        app: redis-cluster-sentinel-lbl
    spec:
      restartPolicy: Always

      containers:
      - name: redis-cluster-sentinel-c1
        image: dikapriska/redis-ha-cluster:latest

        resources:
          requests:
            memory: "100Mi"
            cpu: .2
          limits:
            memory: "200Mi"
            cpu: .5

        imagePullPolicy: IfNotPresent

        ports:
        - containerPort: 26379

        env:
        - name: SENTINEL
          value: "true"
