apiVersion: v1
kind: Service
metadata:
  labels:
    name: redis-cluster-sentinel-service-lbl
  name: redis-cluster-sentinel-service
spec:
  ports:
    - port: 26379
  selector:
    app: redis-cluster-sentinel-lbl

---

apiVersion: v1
kind: Service
metadata:
  labels:
    name: redis-cluster-master-service-lbl
  name: redis-cluster-master-service
spec:
  ports:
    - port: 6379
  selector:
    app: redis-cluster-master-lbl
